name: Docker Image CI bundle

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
  push:
    branches: [ master ]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH
      - name: build docker
        run: docker build -t telegraher-${{ env.AARCH }} -f Dockerfile_${{ env.AARCH }} .
      - name: build app
        run: docker run --rm -v "$PWD":/home/source telegraher-${{ env.AARCH }}
      - name: sha256 basic apk
        run: echo "::set-output name=SHA256BASIC::$(sha256sum ./TMessagesProj/build/outputs/apk/${{ env.AARCH }}/release/app.apk|head -c 64)"
        id: sha256_basic
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.RNAME }} (${{ env.AARCH }})
          tag_name: ${{ env.TNAME }}${{ env.hash }}_${{ env.AARCH }}
          body: BETA Bundle (`arm64_v8a`/`armeabi_v7a`/`x86`/`x86_64`) ${{ env.ANAME }}_${{ env.hash }}_${{ env.AARCH }}.apk (sha256 `${{ steps.sha256_basic.outputs.SHA256BASIC }}`)
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload apk basic
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./TMessagesProj/build/outputs/apk/${{ env.AARCH }}/release/app.apk
          asset_name: ${{ env.ANAME }}_${{ env.hash }}_${{ env.AARCH }}.apk
          asset_content_type: application/gzip
    env:
      RNAME: Telegraher
      TNAME: noshit_
      ANAME: Telegraher
      AARCH: bundle
